FROM koalaphils/php:8-apache

#Install symfony cli
RUN curl -sS https://get.symfony.com/cli/installer | bash
RUN mv /root/.symfony/bin/symfony /usr/local/bin/symfony

ENV APACHE_DOCUMENT_ROOT /var/www/html/public

#Apache changes for document root
RUN sed -ri -e "s|/var/www/html|${APACHE_DOCUMENT_ROOT}|g" $APACHE_CONFDIR/sites-available/*.conf

#Copy codes to html folder
ONBUILD COPY app /var/www/html
#Install composer packages
ONBUILD RUN composer config --global use-github-api false \
  ; rm -rf vendor && mkdir -p vendor && php -d memory_limit=-1 `which composer` install -no --apcu-autoloader --no-scripts --no-progress --no-autoloader --no-cache \
  ;
ONBUILD RUN composer dumpautoload -no --apcu --no-scripts \
  ;
ONBUILD VOLUME /var/www/html/vendor
