ARG PHP_VERSION=8
FROM ghcr.io/koalaphils/php:${PHP_VERSION}-apache

COPY --link --from=composer/composer /usr/bin/composer /usr/local/bin/composer
ENV APACHE_DOCUMENT_ROOT=/var/www/html/public

COPY opt/php/*.ini $PHP_INI_DIR/conf.d/
RUN set -eux; \
    apt-get update && apt-get install -y --no-install-recommends git &&  \
    php -n `which composer` config --global use-github-api false \
    ; git config --global --add safe.directory /var/www/html \
    ; docker-php-ext-enable \
      apcu \
      ev \
      gd \
      intl \
      pcntl \
      xsl \
      zip \
    ;

#Install symfony cli
RUN curl -sS https://get.symfony.com/cli/installer | bash -s - --install-dir /usr/local/bin

#Apache changes for document root
RUN sed -ri -e "s|/var/www/html|${APACHE_DOCUMENT_ROOT}|g" $APACHE_CONFDIR/sites-available/*.conf

#Copy codes to html folder
ONBUILD COPY app /var/www/html

#Install composer packages
ONBUILD RUN rm -rf vendor && mkdir -p vendor \
  ; symfony composer install --no-scripts --no-autoloader || exit 1 \
  ; symfony composer dumpautoload -no --apcu --no-scripts --classmap-authoritative \
  ; symfony composer run-script post-install-cmd \
  ; symfony check:requirements || exit 1 \
  ; symfony version || exit 1 \
  ;
ONBUILD VOLUME /var/www/html/vendor
